# Generated by Django 5.0.7 on 2024-07-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
