# Generated by Django 5.0.7 on 2024-07-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecs', '0002_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='freecs.course')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecs.member')),
            ],
        ),
    ]
