# Generated by Django 5.0.7 on 2024-07-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freecs', '0005_rename_preferance_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_date',
        ),
    ]
