# Generated by Django 5.0.7 on 2024-07-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freecs', '0006_remove_member_email_remove_member_membership_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
