# Generated by Django 5.0.7 on 2024-07-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecs', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freecs.member'),
        ),
    ]
