# Generated by Django 5.0.7 on 2024-08-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecs', '0008_alter_preference_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freecs.member')),
            ],
        ),
    ]
