# Generated by Django 5.0.7 on 2024-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecs', '0009_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
